### ISSUE TITLE
mistake in D(x,z) input size

### ISSUE THREAD

**Issue by edgarriba** [IshmaelBelghazi/ALI#10]
In table 5 from the paper you state that the input size for `D(x,z)` is `1024x1x1` which I think it's wrong after looking at the previous output sizes `D(x)` and `D(z)`. I think that should be `1536x1x1`.

Is that assumption correct?

**Comment by edgarriba** [comment]
ping @IshmaelBelghazi @vdumoulin

**Comment by vdumoulin** [comment]
Sorry for the delay; I'll have a short look at get back at you on this.

**Comment by vdumoulin** [comment]
@edgarriba You are absolutely correct, thank you for pointing this out!

**Comment by hubert0527** [comment]
I have a similar problem about the hyper-parameters in Table 5.

The output feature map channel of G_z(x) (i.e. 512) is supposed to be 2 times the size of the latent vector dimension (due to the VAE architecture).
But G_x(z) shows that the latent vector size is 512, instead of 256.
I'm not sure which one is wrong? Or I misunderstand something?
Thanks!

**Comment by vdumoulin** [comment]
@hubert0527 comparing Table 5 in the paper and the [relevant portion](https://github.com/IshmaelBelghazi/ALI/blob/master/experiments/ali_celeba.py#L31) of the source code, I believe there is a typo in Table 5: `G_x(z) – 512 × 1 × 1 input` should instead read `G_x(z) – 256 × 1 × 1 input`.

Thanks for pointing it out, and sorry about the confusion!
